# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  main: openapi/channel.yaml
  communication: openapi/communication.yaml
  workflow: openapi/workflow.yaml
  interaction: openapi/interaction.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
