openapi: 3.1.0
info:
  title: Communication Channel Api
  description: Manage account's communication properties
  version: '1.0-preview'  
servers:
  - url: 'https://{gigya-domain}'
    variables:
      gigya-domain:
        default: accounts.gigya.com
        enum:
          - accounts.gigya.com
          - accounts.eu1.gigya.com
          - accounts.au1.gigya.com
        description: giya domains
        
components:
  securitySchemes:
    apiKey:
       $ref: ./shared/securitySchemes/apiKey.yaml
    uid:
      $ref: ./shared/securitySchemes/uid.yaml   
    basic:
      $ref: ./shared/securitySchemes/basic.yaml
    oauth: # <---- OAuth flow(authorizationCode, implicit, password or clientCredentials)
      $ref: ./shared/securitySchemes/oauth.yaml


security:
  - oauth: []
  - apiKey: []
    uid: []
    basic: []
    
paths:
 
  /accounts.setAccountInfo:
    $ref: account-subscription\paths\setAccountInfo.yaml
  
  /accounts.getAccountInfo:
    $ref: account-subscription\paths\getAccountInfo.yaml
  
  /accounts.search:
    $ref: 'account-subscription\paths\search.yaml'
  
  '/config/communication/v1/':
    $ref: 'channel-schema\paths\lists.yaml'
  '/config/communication/v1/lists/{listId}':
    $ref: 'channel-schema\paths\lists@{listId}.yaml'
  '/config/communication/v1/lists/{listId}/fields':
    $ref: 'channel-schema\paths\lists@{listId}@fields.yaml'
  '/config/communication/v1/lists/{listId}/channel':
    $ref: 'channel-schema\paths\lists@{listId}@fields@channel.yaml'
  '/config/communication/v1/lists/{listId}/fields/{fieldId}':
    $ref: 'channel-schema\paths\lists@{listId}@fields@{fieldId}.yaml'
  
 
tags:
  - name: communication
    x-displayName: Communication
    description: |
      Operations to update communication properties
      
  - name: search
    x-displayName: Search
    description: |
      Search communication preferences
  - name: communication-model
    x-displayName: Communication Model
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/communication" showReadOnly={true} showWriteOnly={true} />
  - name: basic_search_response
    x-displayName: Search Response
    description: |
      <OpenApiResponse schemaRef="#/components/schemas/basic_search_response" showReadOnly={true} showWriteOnly={true} />

  - name: communication-entry
    x-displayName: Communication Entry
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/communication-entry" showReadOnly={true} showWriteOnly={true} />
  - name: communication-model-cdp
    x-displayName: Communication CDP
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/communication-cdp" showReadOnly={true} showWriteOnly={true} />

x-tagGroups:
  - name: Communication Runtime
    tags:
      - communication
      
  - name: Communication Search
    tags:
      - search

  # - name: Communication Management
  #   tags:
  #     - Config
    
  - name: Models
    tags:
      - communication-model
      - communication-entry
 

    

 
 
 
