openapi: 3.1.0
info:
  title: Communication Channel Api
  description: Api manges customer channel lists.
  version: '1.0'
servers:
  - url: 'https://{gigya-domain}/me'
    variables:
      gigya-domain:
        default: accounts.gigya.com
        enum:
          - accounts.gigya.com
          - accounts.eu1.gigya.com
          - accounts.au1.gigya.com
        description: giya domains
        
components:
  securitySchemes:
    apiKey:
       $ref: ./shared/securitySchemes/apiKey.yaml
    uid:
      $ref: ./shared/securitySchemes/uid.yaml   
    basic:
      $ref: ./shared/securitySchemes/basic.yaml
    oauth: # <---- OAuth flow(authorizationCode, implicit, password or clientCredentials)
      $ref: ./shared/securitySchemes/oauth.yaml


security:
  - oauth: []
  - apiKey: []
    uid: []
    basic: []
    
paths:
  /channels:
    $ref: account-subscription\paths\channels.yaml
#  /channels:
#    $ref: account-subscription\paths\channels@option2.yaml
  '/channels/{channel}/lists/{list}/opt-in':
    $ref: 'account-subscription\paths\channels@{channel}@lists@{list}@opt-in.yaml'
  '/channels/{channel}/lists/{list}/opt-out':
    $ref: 'account-subscription\paths\channels@{channel}@lists@{list}@opt-out.yaml'
  '/channels/{channel}/opt-in':
    $ref: 'account-subscription\paths\channels@{channel}@opt-in.yaml'
  '/channels/{channel}/opt-out':
    $ref: 'account-subscription\paths\channels@{channel}@opt-out.yaml'

tags:
  - name: communication
    x-displayName: Communication
    description: Operations to update communication properties
  - name: list
    x-displayName: Lists
    description:  Operations to update communication lists of account
  - name: channel
    x-displayName: Channel
    description: Operations to update communication channels 

  - name: channel_model
    x-displayName:  Channel 
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/channel" />
  - name: lists_model
    x-displayName: Lists 
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/lists" showReadOnly={true} showWriteOnly={true} />
  - name: list_model
    x-displayName: List
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/list"  showReadOnly={true} showWriteOnly={true} />
  - name: status_model
    x-displayName: Status
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/status" showReadOnly={true} showWriteOnly={true} />

x-tagGroups:
  - name: Communication Management
    tags:
      - communication
      - channel
      - list

  - name: Models
    tags:
      - status_model 
      - channel_model
      - list_model
      - lists_model

 
 
 
