openapi: 3.1.0
info:
  title: Communication Channel Api
  description: Manage account's communication properties
  version: '1.0'
servers:
  - url: 'https://{gigya-domain}/accounts/{_me}/communication/{v1}/'
    variables:
      gigya-domain:
        default: accounts.gigya.com
        enum:
          - accounts.gigya.com
          - accounts.eu1.gigya.com
          - accounts.au1.gigya.com
        description: giya domains
        
components:
  securitySchemes:
    apiKey:
       $ref: ./shared/securitySchemes/apiKey.yaml
    uid:
      $ref: ./shared/securitySchemes/uid.yaml   
    basic:
      $ref: ./shared/securitySchemes/basic.yaml
    oauth: # <---- OAuth flow(authorizationCode, implicit, password or clientCredentials)
      $ref: ./shared/securitySchemes/oauth.yaml


security:
  - oauth: []
  - apiKey: []
    uid: []
    basic: []
    
paths:
  '/search':
    $ref: 'account-subscription\paths\search.yaml'
  '/actions/patch':
    $ref: 'account-subscription\paths\actions_2.yaml'

  /:
    $ref: account-subscription\paths\channels.yaml
#  /channels:
#    $ref: account-subscription\paths\channels@option2.yaml
  '/{channel}/lists/{list}/opt-in':
    $ref: 'account-subscription\paths\channels@{channel}@lists@{list}@opt-in.yaml'
  '/{channel}/lists/{list}/opt-out':
    $ref: 'account-subscription\paths\channels@{channel}@lists@{list}@opt-out.yaml'
  '/{channel}/lists/{list}/notice':
    $ref: 'account-subscription\paths\channels@{channel}@lists@{list}@notice.yaml'
  '/{channel}/lists/opt-out':
    $ref: 'account-subscription\paths\channels@{channel}@lists@opt-out.yaml'
  '/{channel}/opt-in':
    $ref: 'account-subscription\paths\channels@{channel}@opt-in.yaml'
  '/{channel}/opt-out':
    $ref: 'account-subscription\paths\channels@{channel}@opt-out.yaml'
  '/{channel}/notice':
    $ref: 'account-subscription\paths\channels@{channel}@notice.yaml'
   
  '/lists':
    $ref: 'channel-schema\paths\lists.yaml'
  '/lists/{listId}':
    $ref: 'channel-schema\paths\lists@{listId}.yaml'
  '/lists/{listId}\fields':
    $ref: 'channel-schema\paths\lists@{listId}@fields.yaml'
  '/lists/{listId}\fields\channel':
    $ref: 'channel-schema\paths\lists@{listId}@fields@channel.yaml'
  '/lists/{listId}\fields\{fieldId}':
    $ref: 'channel-schema\paths\lists@{listId}@fields@{fieldId}.yaml'
  '/lists/{listId}?$filter=channel(email)&$expand=Account($select=firstName,email)':
    $ref: account-subscription\paths\query.yaml 

  '/channel-as-attribute':
    $ref: account-subscription\paths\channels@option2.yaml
  '/integrations/mailchimp/lists/{list_id}':                          
    $ref: 'account-subscription\paths\mailchimp.yaml'
  '/integrations/marketo/rest/v1/lists/{listId}/leads.json':
    $ref: account-subscription\paths\marketo.yaml
  '/integrations/marketo/userservice/management/v1/users/{userid}/update.json':
    $ref: account-subscription\paths\marketo-um.yaml
  '/integrations/emarsys/api/v2/contact':
    $ref: 'account-subscription\paths\emarsys.yaml'

tags:
  - name: communication
    x-displayName: Communication
    description: |
      Operations to update communication properties
      
  - name: search
    x-displayName: Search
#  - name: actions
#    x-displayName: Communication Actions
#    description: |
#      Operations to update communication properties
  - name: integrations
    x-displayName: Integrations
    description: |
      Integrations Open API
      https://dev.emarsys.com/docs/emarsys-api/b3A6MjQ4OTk4MDc-create-contacts

#  - name: list
#    x-displayName: Lists
#    description:  Operations to update communication lists of account
#  - name: channel
#    x-displayName: Channel
#    description: Operations to update communication channels 
#  - name: communication-model-2
#    x-displayName: Communication-2
#    description: |
#      <SchemaDefinition schemaRef="#/components/schemas/communication" />
#  - name: channel_model
#    x-displayName:  Channel 
#    description: |
#      <SchemaDefinition schemaRef="#/components/schemas/channel" />
#  - name: lists_model
#    x-displayName: Lists 
#    description: |
#      <SchemaDefinition schemaRef="#/components/schemas/lists" showReadOnly={true} showWriteOnly={true} />
#  - name: list_model
#    x-displayName: List
#    description: |
#      <SchemaDefinition schemaRef="#/components/schemas/list"  showReadOnly={true} showWriteOnly={true} />
#  - name: status_model
#    x-displayName: Status
#    description: |
#      <SchemaDefinition schemaRef="#/components/schemas/status" showReadOnly={true} showWriteOnly={true} />
  - name: communication-model
    x-displayName: Communication Model
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/communication" showReadOnly={true} showWriteOnly={true} />
  - name: communication-model-cdp
    x-displayName: Communication CDP
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/communication-cdp" showReadOnly={true} showWriteOnly={true} />

x-tagGroups:
  - name: Communication Runtime
    tags:
      - communication

  - name: Communication Management
    tags:
      - Config
  
  - name: Communication Search
    tags:
      - search
      
  - name: integrations
    description: |
      Integrations Open API
      https://dev.emarsys.com/docs/emarsys-api/b3A6MjQ4OTk4MDc-create-contacts

    tags:
      - communication-model-cdp
      - mailchimp  
      - marketo
      - emarsys
      
      
#  - name: Communication Other
#    tags:
#      - Communication-2
#      - communication-model-2
#      - query


      
  - name: Models
    tags:
      - communication-model
      - status_model 
      - channel_model
      - list_model
      - lists_model
      - communication-action-model-jsonpatch
      - communication-action-model

 
 
 
