openapi: 3.1.0
info:
  title: Interaction Api
  description: Api specification for manges customer interactions.
  version: '1.0'
servers:
  - url: https://{gigya-domain}
    variables:
      gigya-domain:
        default: accounts.gigya.com
        enum:
          - accounts.gigya.com
          - accounts.eu1.gigya.com
          - accounts.au1.gigya.com
        description: giya domains

paths:
  /interactions.create:
    $ref: mng-interaction\paths\interactions@templates.yaml
  /interactions.input.setSchema:
    $ref: mng-interaction\paths\interactions@input@setSchema.yaml    
  /interactions.input.setIdentity:
    $ref: mng-interaction\paths\interactions@input@setIdentity.yaml    
  
  /interactions/{template}/instances:
    $ref: interaction\paths\interactions@{template}.yaml

tags:
  - name: interaction-template-model
    x-displayName: Template Model
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/template" />
      
  - name: interaction-schema-model
    x-displayName: Schema Model
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/schema" />

  - name: interaction-transitions-model
    x-displayName: Transitions Model
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/transitions" />

x-tagGroups:

  - name: Interaction Management
    tags:
      - Configuration
  - name: Interaction Runtime
    tags:
      - Runtime

  - name: Models
    tags:
      - interaction-template-model
      - interaction-schema-model
      - interaction-transitions-model
   